version: "3"

services:
  app:
    build: .
    environment:
      DB_CONN_URI: "postgresql://postgres:postgres@postgres:5432/postgres"
    ports:
      - 8000:8000
    
    links:
      - postgres

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
