"""profile active

Revision ID: 72a7da982290
Revises: c2ec63f7cad9
Create Date: 2022-08-07 19:43:44.125808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72a7da982290'
down_revision = 'c2ec63f7cad9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('user_profile2', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile2', 'active')
    op.drop_column('user_profile', 'active')
    # ### end Alembic commands ###
