"""test

Revision ID: 6a6617f09900
Revises: 3d1745433113
Create Date: 2024-07-11 19:28:24.248120

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6a6617f09900"
down_revision = "3d1745433113"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agg_profile_a0503f02df_meta",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("is_success", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "user_lang_test",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("lang", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("user_id", "lang"),
    )
    op.create_table(
        "user_lang_test_meta",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("lang", sa.String(length=100), nullable=False),
        sa.Column("hash", sa.Integer(), nullable=True),
        sa.Column("create_ts", sa.Float(), nullable=True),
        sa.Column("update_ts", sa.Float(), nullable=True),
        sa.Column("process_ts", sa.Float(), nullable=True),
        sa.Column("delete_ts", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("user_id", "lang"),
    )
    op.drop_table("agg_profile_e8ae44cba1_meta")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agg_profile_e8ae44cba1_meta",
        sa.Column("user_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "process_ts",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("is_success", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("priority", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("error", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("user_id", name="agg_profile_e8ae44cba1_meta_pkey"),
    )
    op.drop_table("user_lang_test_meta")
    op.drop_table("user_lang_test")
    op.drop_table("agg_profile_a0503f02df_meta")
    # ### end Alembic commands ###
